### PR TITLE
Use fill-keys to copy properties from source to stub

### LINKED ISSUE #32: Cannot stub a property with a value of false
To start with, thank you so much for the effort you've put into this module! It's *exactly* what I need for a current project.

I am running into one issue. In my project, I have a JSON file on disk that I `require` into modules. I'm attempting to use `proxyquireify` to overwrite values in this config. This has worked great, except for the use-case where I want to overwrite a value to `false`.

Example:
```javascript
var stubs = {
	'./config.json': {
		flag1: false, // true in config.json itself
		featureName: 'test name' // set to something else in config.json
	}
};
```
With the stubs above, I get the following behavior:

1. `featureName` is set to `'test name'` as expected
2. `flag1` is still true (should be false)

I'm *guessing* that `proxyquireify` does a truthy check when looping over each stub in a file, to check if it actually exists.

### PR DESCRIPTION
**Pull request by bendrucker**
* Aligns p-ify with proxyquire
* Correctly handles falsy stub values

Closes #32 

Ready for review @thlorenz

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM, nice work!
Is the plan to use fill-keys in proxyquire as well to get consistent behavior? That'd be good.

Please merge, I'll publish tomorrow.

**Comment by bendrucker** [comment]
Correct, via thlorenz/proxyquire#65

**Comment by thlorenz** [comment]
LGTM.

**Comment by thlorenz** [comment]
Published as minor upgrade for [similar reasons](https://github.com/nodesource/education/blob/master/courses/f5/fundamentals.json)

BTW noticed when running the tests with iojs (which errors for wrong reason) that peer test range still reported all tests as passed.
Is that a bug?
We need to make sure that failed tests are reported correctly (also on travis).

Here is how to repro (assuming you have `n` installed):

```
n io 2.0
npm test
```

You will see some tests failing but test peer range will report that all passed.

**Comment by bendrucker** [comment]
Cool. So the issue with the tests is actually not related to peer-range. `node test/clientside/run.js && echo $?` returns `0` even though there are failures. 

https://github.com/substack/tape/blob/25cd3dee215d86a70571fe3faa34e60821abffe8/index.js#L7-L12

Should be a pretty simple fix

**Comment by thlorenz** [comment]
Ah ok, darn I ran into this so many times already. With tape mostly actually.
We're using tap here though.
We could try to run our tests [one by one and trap the error](https://github.com/thlorenz/gai/blob/master/package.json#L6) unless we can get it to work via tap.

**Comment by bendrucker** [comment]
I'll look into this. Part of the issue is that browserify feeds in a process shim and then all the normal exit code management stops, even with `vm.runInNewContext`. So the options are to pass `{detectGlobals: false}` and manually pass through the globals or try to parse stdout and exit appropriately. I'll try the former and revert to the latter as a last resort.

**Comment by bendrucker** [comment]
First rule of programming...

It's a race condition. Even when you pass in `process`, every bundle gets its own tape. And so the first to exit wins. Sometimes the end result is a failure, sometimes it passes. I think the best approach here is just to pass through tape as a global.

**Pull request merged**
