### PR TITLE
Use test-peer-range to test major browserify versions

### PR DESCRIPTION
**Pull request by bendrucker**

### CODE REVIEW

**Comment by bendrucker** [comment]
There's a bug with `>=x` ranges. Will update.

**Comment by thlorenz** [comment]
> Will update.
peer-range has that bug I suppose?

Other than that LGTM.

**Comment by bendrucker** [comment]
Correct. The npm API is super unreliable and halfway documented.

**Comment by bendrucker** [comment]
Fixed. This actually reveals a proxyquireify test failing against browserify@10. Will look into that.

**Pull request merged**
