### PR TITLE
Attempt to parse all non-JSON files

### PR DESCRIPTION
**Pull request by bendrucker**
Commit message fully explains the change and its implications as discussed in #24

### CODE REVIEW

**Comment by bendrucker** [comment]
@thlorenz How do you want to handle this? I think the way it's handled here (assume files are valid js unless they're json) is the best. Forcing users to manually add extensions to match does mean that setups that take some string and turn it into simple JS that returns a string (e.g. a sass transform) won't break. On the other hand, for alternate scripting languages, e.g. TypeScript or CoffeeScript, it still means the AST parse will fail if the transforms aren't ordered properly. 

There's no harm in doing a major version bump though.

**Comment by thlorenz** [comment]
LGTM, let's add a huge warning to the Readme though as well.

**Comment by bendrucker** [comment]
You think b7a58f4253d19bd94dd5312daadc44f4387c1332 is enough?

**Comment by thlorenz** [comment]
I'd like it to be more _in my face_ so to speak (people don't read entire docs ever).

Could we have a `## Warning` or `## Caveats` header? Or maybe `## Using proxyquireify along other transforms`?
That way we could also link it in the TOC to make it easy to find.

**Comment by bendrucker** [comment]
Fair enough -- how's 55caf84261073a8d176fe21c52a8fedb9b2ad54c?

**Comment by thlorenz** [comment]
Awesome, LGTM.
Feel free to merge all this now.

**Comment by bendrucker** [comment]
Done, ready for a major bump

**Comment by thlorenz** [comment]
Published, thanks.

**Pull request merged**
